# Generated by Django 2.2.9 on 2020-05-10 17:34

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.BaseModel')),
                ('title', models.CharField(max_length=250)),
                ('index_image', models.ImageField(blank=True, null=True, upload_to='blog/index_image/')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('category', models.ManyToManyField(to='blog.CategoryModel')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'PostModel',
            },
            bases=('blog.basemodel',),
        ),
    ]
