# Generated by Django 2.2.9 on 2020-05-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contactformmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
