# Generated by Django 2.2.9 on 2020-06-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200613_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformmodel',
            options={'verbose_name': 'Contact Form', 'verbose_name_plural': 'Contact Forms'},
        ),
        migrations.AlterModelTable(
            name='contactformmodel',
            table='ContactFormModel',
        ),
    ]
