# Generated by Django 2.2.9 on 2020-06-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200613_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='index_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
